'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating creative prompts.
 *
 * - generateCreativePrompt - A function that generates a creative prompt.
 * - GenerateCreativePromptInput - The input type for the generateCreativePrompt function.
 * - GenerateCreativePromptOutput - The output type for the generateCreativePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCreativePromptInputSchema = z.object({
  topic: z.string().optional().describe('Optional topic to inspire the prompt.'),
});
export type GenerateCreativePromptInput = z.infer<
  typeof GenerateCreativePromptInputSchema
>;

const GenerateCreativePromptOutputSchema = z.object({
  prompt: z.string().describe('A creative prompt generated by the AI.'),
});
export type GenerateCreativePromptOutput = z.infer<
  typeof GenerateCreativePromptOutputSchema
>;

export async function generateCreativePrompt(
  input: GenerateCreativePromptInput
): Promise<GenerateCreativePromptOutput> {
  return generateCreativePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCreativePromptPrompt',
  input: {schema: GenerateCreativePromptInputSchema},
  output: {schema: GenerateCreativePromptOutputSchema},
  prompt: `You are a creativity assistant designed to help users overcome creative block.

  Generate a creative prompt to inspire the user.
  The prompt should be open-ended and encourage exploration.

  {{#if topic}}
  The prompt should be related to the topic: {{{topic}}}
  {{/if}}

  The prompt should be no more than 2 sentences.
  `,
});

const generateCreativePromptFlow = ai.defineFlow(
  {
    name: 'generateCreativePromptFlow',
    inputSchema: GenerateCreativePromptInputSchema,
    outputSchema: GenerateCreativePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
